import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
import Header from "../src/components/generic/Header";
import Separator from "../src/components/generic/Separator";
import Waitlist from "../src/components/landing/Waitlist";
import FeatureGrid from "../src/components/landing/FeatureGrid";
import FeatureSection from "../src/components/landing/FeatureSection";
import HowItWorks from "../src/components/landing/HowItWorks";
import Pricing from "../src/components/landing/Pricing";
import FAQ from "../src/components/landing/FAQ";
import CTA from "../src/components/landing/CTA";
import Footer from "../src/components/generic/Footer";
import AOS from "aos";
import "aos/dist/aos.css";
import { Link, Button, Element, Events, animateScroll as scroll, scrollSpy, scroller  } from 'react-scroll'

export default function Home() {
	useEffect(() => {
		AOS.init({
			offset: 200,
			duration: 750,
		});
	}, []);

	return (
		<div>
			<Head>
				<title>ИдеяШанс</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>{dom.css()}</style>
			</Head>
			<main className="bg-white">
				<Header />
				<div
					data-aos="fade-up"
					className="px-4 bg-gradient-to-b from-white to-primary"
				>
					<div className="text-center max-w-2xl m-auto pt-32 md:pt-40">
						<h1 className="text-6xl md:text-7xl font-bold text-midnight-blue mb-16">
						Веб-сервис для регистрации студенческих
							<span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-primary">
								{` проектов!`}
							</span>
						</h1>
						<p className="text-2xl font-medium text-gray-600 my-8">
						Добро пожаловать на наш веб-сервис для регистрации студенческих проектов! Мы предоставляем уникальную платформу, которая облегчает процесс регистрации проектов, а также отслеживание участия и успешной реализации идей студентов.
						</p>
						<Waitlist />
					</div>

					<div className="flex">

{/* Блок "Добавление проекта" */}
<div className="w-96 mx-auto max-w-xl max-w-md mx-auto bg-white rounded p-8 shadow-md mb-4 mr-4">
  <h2 className="text-2xl font-semibold mb-1 text-green-500 mb-4">Добавление проекта</h2>
  <form action="#" method="POST">
	<div className="mb-4">
	  <label htmlFor="projectName" className="block text-gray-700 text-sm font-bold mb-2 text-green-500">Название проекта:</label>
	  <textarea id="projectName" name="projectName" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" rows="1" required></textarea>
	</div>
	<div className="mb-4">
	  <label htmlFor="projectDescription" className="block text-gray-700 text-sm font-bold mb-2 text-green-500">Описание проекта:</label>
	  <textarea id="projectDescription" name="projectDescription" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" rows="4" required></textarea>
	</div>
	<div className="flex items-center justify-between">
	  <button type="submit" className="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-700 focus:outline-none focus:shadow-outline-green">Добавить проект</button>
	  <a href="#" className="text-gray-500 hover:underline">Отмена</a>
	</div>
  </form>
</div>

{/* Блок "Редактировать проект" */}
<div className="w-96 mx-auto max-w-xl max-w-md mx-auto bg-white rounded p-8 shadow-md mb-4 mr-4">
  <h2 className="text-2xl font-semibold mb-6 text-green-500">Редактировать проект</h2>
  <form action="#" method="POST">
	<div className="mb-4">
	  <h3 className="block text-gray-700 text-sm font-bold mb-2 text-green-500">Изменение описания проекта</h3>
	  <textarea id="editProjectDescription" name="editProjectDescription" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" rows="4" required></textarea>
	</div>
	<div className="mb-4">
	  <h3 className="block text-gray-700 text-sm font-bold mb-2 text-green-500">Изменение статуса проекта</h3>
	  <select id="editProjectStatus" name="editProjectStatus" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required>
		<option value="in_progress">В процессе</option>
		<option value="completed">Завершен</option>
		<option value="pending">Ожидание</option>
	  </select>
	</div>
	<div className="flex items-center justify-end">
	  <button type="submit" className="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-700 focus:outline-none focus:shadow-outline-green">Сохранить изменения</button>
	</div>
  </form>
</div>

{/* Блок "Пригласить в проект" */}
<div className="w-96 mx-auto max-w-xl max-w-md mx-auto bg-white rounded p-8 shadow-md mb-4">
  <h2 className="text-2xl font-semibold mb-6 text-green-500">Пригласить в проект</h2>
  <form action="#" method="POST">
	<div className="mb-4">
	  <label htmlFor="inviteEmail" className="block text-gray-700 text-sm font-bold mb-2">Email пользователя:</label>
	  <input type="email" id="inviteEmail" name="inviteEmail" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" required />
	</div>
	<div className="mb-4">
	  <label htmlFor="inviteMessage" className="block text-gray-700 text-sm font-bold mb-2">Сообщение приглашения:</label>
	  <textarea id="inviteMessage" name="inviteMessage" className="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500" rows="4"></textarea>
	</div>
	<div className="flex items-center justify-end">
	  <button type="submit" className="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-700 focus:outline-none focus:shadow-outline-green">Пригласить в проект</button>
	</div>
  </form>
</div>

</div>
					<div className="m-auto max-w-2xl py-16" data-aos="fade-up">
						<h2 className="text-white text-5xl md:text-6xl font-bold mt-4 text-center">
						О нас
						</h2>
						<p className="text-center text-2xl font-medium my-8 text-white">
						Наши возможности созданы с учетом потребностей современных учебных заведений, студентов и преподавателей. Мы стремимся поддерживать креативность и инновации, предоставляя удобные инструменты для воплощения в жизнь учебных проектов.
						</p>
					</div>
				</div>

			
				<div className="bg-white py-8 md:py-16" data-aos="fade-up">
					<div className="m-auto max-w-2xl py-16">
						<h2 className="text-midnight-blue text-5xl md:text-6xl font-bold mt-4 text-center">
						Основные функции
						</h2>
						<p className="text-center text-2xl font-medium mt-8 text-gray-600">
						Регистрация проектов: Простой и интуитивно понятный процесс регистрации проектов, который поможет вам быстро запустить свою идею.
						</p>
						<p className="text-center text-2xl font-medium mt-8 text-gray-600">
						Отслеживание участия: Возможность следить за вовлеченностью участников в проект, устанавливать задачи и отмечать их выполнение.
						</p>
						<p className="text-center text-2xl font-medium mt-8 text-gray-600">
						Мониторинг реализации: Отслеживайте этапы реализации проекта, просматривайте достижения и регулируйте планы действий.
						</p>
					</div>
				</div>
				<div className="py-8 md:py-16 mt-8 md:mt-16" data-aos="fade-up">
					<HowItWorks 
						title="Загрузите свой первый проект"
						subtitle="Добро пожаловать в захватывающий мир творчества и инноваций! Мы приглашаем вас начать свой увлекательный путь с нами, загрузив свой первый проект. Это быстро, просто и, самое главное, вдохновляюще!"
					/>
				</div>
				<div className="py-8 md:py-16 px-4" data-aos="fade-up">
					<FAQ />
				</div>
				<div className="py-8 md:py-16 px-4" data-aos="fade-up" onClick={() => scroll.scrollToTop()}>
					<CTA
						title="Стартуйте свой путь к успеху!"
						subtitle="Не откладывайте на потом свои творческие идеи. Загрузите свой первый проект прямо сейчас и вместе мы сделаем образование более интересным и практичным!"
						onCTAClick={scroll.scrollToTop}
					/>
				</div>
				<Footer />
			</main>
		</div>
	);
}

